/*NIBM EAD CW2 Group Project*/
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pkgfinal;
import java.sql.*;
import javax.swing.JOptionPane;
/**
 *
 * @author isuri
 */
public class TeacherRecords extends javax.swing.JFrame {

    /**
     * Creates new form TeacherRecords
     */
    public TeacherRecords() {
        initComponents();
        Name.setEnabled(false);
        Dept.setEnabled(false);
        ddob.setEnabled(false);
        mdob.setEnabled(false);
        ydob.setEnabled(false);
        Cno.setEnabled(false);
        Add.setEnabled(false);
        Post.setEnabled(false);
        Sal.setEnabled(false);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Tid = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        ddob = new javax.swing.JComboBox<>();
        mdob = new javax.swing.JComboBox<>();
        ydob = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        Cno = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        Add = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Dept = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        Post = new javax.swing.JComboBox<>();
        jLabel9 = new javax.swing.JLabel();
        Sal = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();

        jButton7.setText("jButton7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Teachers' Records");
        setMinimumSize(new java.awt.Dimension(630, 570));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Monotype Corsiva", 2, 24)); // NOI18N
        jLabel1.setText("Teacher ID :");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(23, 27, 120, 26);

        Tid.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        getContentPane().add(Tid);
        Tid.setBounds(150, 30, 80, 27);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Records", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Monotype Corsiva", 2, 24))); // NOI18N
        jPanel1.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel2.setText("Name :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(10, 40, 60, 24);

        Name.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jPanel1.add(Name);
        Name.setBounds(120, 40, 280, 27);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel3.setText("DOB :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 120, 44, 21);

        ddob.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        ddob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jPanel1.add(ddob);
        ddob.setBounds(120, 120, 48, 27);

        mdob.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        mdob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December" }));
        jPanel1.add(mdob);
        mdob.setBounds(170, 120, 99, 27);

        ydob.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        ydob.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1956", "1957", "1958", "1959", "1960", "1961", "1960", "1962", "19603", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995" }));
        jPanel1.add(ydob);
        ydob.setBounds(270, 120, 72, 27);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel4.setText("Contact No.(s) :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(10, 160, 102, 21);

        Cno.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        Cno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CnoActionPerformed(evt);
            }
        });
        jPanel1.add(Cno);
        Cno.setBounds(120, 160, 200, 27);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel5.setText("Address :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(10, 200, 60, 21);

        Add.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jPanel1.add(Add);
        Add.setBounds(120, 200, 200, 27);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel7.setText("Department :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, 80, 88, 21);

        Dept.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        Dept.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computing", "Design", "Management" }));
        jPanel1.add(Dept);
        Dept.setBounds(120, 80, 117, 27);

        jLabel8.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel8.setText("Position :");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(10, 240, 70, 21);

        Post.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        Post.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lecturer", "Cordinator" }));
        jPanel1.add(Post);
        Post.setBounds(120, 240, 99, 27);

        jLabel9.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel9.setText("Salary :");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(10, 280, 49, 21);

        Sal.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jPanel1.add(Sal);
        Sal.setBounds(120, 280, 120, 27);

        jLabel11.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Untitled24.png"))); // NOI18N
        jPanel1.add(jLabel11);
        jLabel11.setBounds(240, 30, 350, 300);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(10, 100, 600, 340);

        jButton1.setBackground(new java.awt.Color(0, 204, 204));
        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(102, 0, 102));
        jButton1.setText("Get Records");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(370, 30, 130, 50);

        jButton2.setBackground(new java.awt.Color(255, 102, 0));
        jButton2.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(102, 0, 102));
        jButton2.setText("Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(10, 490, 80, 29);

        jButton3.setBackground(new java.awt.Color(255, 102, 0));
        jButton3.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(102, 0, 102));
        jButton3.setText("Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(470, 490, 80, 29);

        jButton4.setBackground(new java.awt.Color(0, 204, 204));
        jButton4.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(102, 0, 102));
        jButton4.setText("Clear");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(370, 450, 90, 29);

        jButton5.setBackground(new java.awt.Color(0, 204, 204));
        jButton5.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 0, 102));
        jButton5.setText("Update");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(140, 450, 100, 29);

        jButton6.setBackground(new java.awt.Color(0, 204, 204));
        jButton6.setFont(new java.awt.Font("Monotype Corsiva", 2, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 0, 102));
        jButton6.setText("Delete");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(260, 450, 90, 29);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/bg1.jpg"))); // NOI18N
        jLabel6.setText("jLabel6");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(-9, -10, 660, 560);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        // TODO add your handling code here:
        Date dob;
        String tid,nm,dept,cno,add,post,sal,dd,mm,yy,month;
        tid = Tid.getText();
        if(tid.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please enter the Teacher ID","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try{
                Class.forName("com.mysql.jdbc.Driver");

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schooladmin",
                                                             "root",
                                                             "");
                Statement stmt = con.createStatement();
                
                
                String query = "Select * from teacher1 where Tid = '" +tid+ "'";

                ResultSet rs = stmt.executeQuery(query);

                Tid.setEnabled(false);

                if(rs.next())
                {
                    nm = rs.getString("Name");
                    dept = rs.getString("Dept");
                    dob = rs.getDate("DOB");
                    cno = rs.getString("Cno");
                    add = rs.getString("Address");
                    post = rs.getString("Position");
                    sal = rs.getString("Salary");
                    Name.setText(nm);
                    Cno.setText(cno);
                    Add.setText(add);
                    Sal.setText(sal);
                    Dept.setSelectedItem(dept);
                    ddob.setSelectedIndex(dob.getDate()-1);
                    mdob.setSelectedIndex(dob.getMonth());
                    ydob.setSelectedIndex(dob.getYear()-56);
                    Post.setSelectedItem(post);
                    Name.setEnabled(true);
                    Tid.setEnabled(false);
                    Dept.setEnabled(true);
                    ddob.setEnabled(true);
                    mdob.setEnabled(true);
                    ydob.setEnabled(true);
                    Cno.setEnabled(true);
                    Add.setEnabled(true);
                    Post.setEnabled(true);
                    Sal.setEnabled(true);
                }else
                {
                    JOptionPane.showMessageDialog(this, "ID not found","ERROR",JOptionPane.ERROR_MESSAGE);
                    Tid.setText("");
                    Tid.setEnabled(true);
                }


            }catch(ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this, e,"ERROR",JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void CnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CnoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        new TeacherHome().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         JOptionPane.showMessageDialog(this,"Thank You For Using" + "\n"
                                        + "Good Bye" + "\n");
                                       
         System.exit(0);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        Tid.setText("");
        Name.setText("");
        Cno.setText("");
        Add.setText("");
        Sal.setText("");
        Dept.setSelectedIndex(0);
        ddob.setSelectedIndex(0);
        mdob.setSelectedIndex(0);
        ydob.setSelectedIndex(0);
        Post.setSelectedIndex(0);
        Tid.setEnabled(true);
        Name.setEnabled(false);
        Dept.setEnabled(false);
        ddob.setEnabled(false);
        mdob.setEnabled(false);
        ydob.setEnabled(false);
        Cno.setEnabled(false);
        Add.setEnabled(false);
        Post.setEnabled(false);
        Sal.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        String tid,nm,dept,deptno,cno,add,post,sal,dd,mm,yy,month,dob;
        tid = Tid.getText();
        if(tid.isEmpty())
        {
             JOptionPane.showMessageDialog(this,"Please enter the Teacher ID","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            
            nm = Name.getText();
            dept = (String) Dept.getSelectedItem();
            cno = Cno.getText();
            add= Add.getText();
            post = (String) Post.getSelectedItem();
            sal = Sal.getText();
            dd = (String)ddob.getSelectedItem();
            month = (String)mdob.getSelectedItem();
            mm = "01";                             //Should be changed
            switch (month)
                            {
                                case "January"  : mm = "01";
                                break;
                                case "February" : mm = "02";
                                break;
                                case "March"    : mm = "03";
                                break;
                                case "April"    : mm = "04";
                                break;
                                case "May"      : mm = "05";
                                break;
                                case "June"     : mm = "06";
                                break;
                                case "July"     : mm = "07";
                                break;
                                case "August"   : mm = "08";
                                break;
                                case "September": mm = "09";
                                break;
                                case "October"  : mm = "10";
                                break;
                                case "November" : mm = "11";
                                break;
                                case "December" : mm = "12";
                                break;
                            }
            yy = (String)ydob.getSelectedItem();
            dob = yy+"/"+mm+"/"+dd;
            if(nm.isEmpty()||cno.isEmpty()||add.isEmpty()||sal.isEmpty())
            {
             JOptionPane.showMessageDialog(this,"Please fill all the Entries","Error",JOptionPane.ERROR_MESSAGE);   
            }
            else
            {
                try{
                Class.forName("com.mysql.jdbc.Driver");

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schooladmin",
                                                             "root",
                                                             "");

                Statement stmt = con.createStatement();

                String query = "Update teacher1 set Name = '" +nm+ "',Dept ='" +dept+ "',DOB ='" +dob+"',Cno ='" +cno+"', Address ='" +add+ "',Position ='" +post+ "',Salary ='" +sal+"' where Tid ='" +tid+ "'";

                stmt.executeUpdate(query);

                JOptionPane.showMessageDialog(this, "Successfully Updated","Update",JOptionPane.PLAIN_MESSAGE);    
                }catch(ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this,e,"ERROR",JOptionPane.ERROR_MESSAGE);}
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        String tid = Tid.getText();
        if(tid.isEmpty())
        {
            JOptionPane.showMessageDialog(this,"Please enter the Teacher ID","Error",JOptionPane.ERROR_MESSAGE);
        }
        else
        {
            try{
                Class.forName("com.mysql.jdbc.Driver");

                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/schooladmin",
                                                             "root",
                                                             "");

                Statement stmt = con.createStatement();
                
                String check = "Select * from teacher1";
                        
                String query = "Delete from teacher1 where Tid ='" +tid+"'";
                
                ResultSet rs = stmt.executeQuery(check);
                if(rs.next())
                {
                    int confirm = JOptionPane.showConfirmDialog(this,"Are you sure you want to Delete this Record","Confirm",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);
                    
                    if(confirm==JOptionPane.YES_OPTION)
                    {
                        stmt.executeUpdate(query);

                        JOptionPane.showMessageDialog(this, "Successfully Deleted","Delete",JOptionPane.PLAIN_MESSAGE);
                        Tid.setText("");
                        Name.setText("");
                        Cno.setText("");
                        Add.setText("");
                        Sal.setText("");
                        Dept.setSelectedIndex(0);
                        ddob.setSelectedIndex(0);
                        mdob.setSelectedIndex(0);
                        ydob.setSelectedIndex(0);
                        Post.setSelectedIndex(0);
                        Tid.setEnabled(true);
                        Name.setEnabled(false);
                        Dept.setEnabled(false);
                        ddob.setEnabled(false);
                        mdob.setEnabled(false);
                        ydob.setEnabled(false);
                        Cno.setEnabled(false);
                        Add.setEnabled(false);
                        Post.setEnabled(false);
                        Sal.setEnabled(false);
                    }
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Teacher ID not found","ERROR",JOptionPane.ERROR_MESSAGE);
                }
                }catch(ClassNotFoundException | SQLException e){JOptionPane.showMessageDialog(this,e,"ERROR",JOptionPane.ERROR_MESSAGE);}
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TeacherRecords.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
       java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TeacherRecords().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Add;
    private javax.swing.JTextField Cno;
    private javax.swing.JComboBox<String> Dept;
    private javax.swing.JTextField Name;
    private javax.swing.JComboBox<String> Post;
    private javax.swing.JTextField Sal;
    private javax.swing.JTextField Tid;
    private javax.swing.JComboBox<String> ddob;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> mdob;
    private javax.swing.JComboBox<String> ydob;
    // End of variables declaration//GEN-END:variables
}
